### ISSUE TITLE
[FEATURE REQ] Status Banner

### ISSUE THREAD

**Issue by big610** [Rllyyy/Internet-Check#95]
[FEATURE REQ] Status Banner
I have the need for an App that alerts me when my Internet Tower goes down, and then when it comes back on, both myself, the Provider, Owner need to know to the second, as it effects everyone else.

I had been searching Github for this category awhile, was happy to finally find the debut First Release Apr 25 2020.
I have both Mac & Windows.
For macOS the only App in this same category is perfect. I hope these features can be added:
https://appyogi.com/webapps/index.php?product_id=49
https://apps.apple.com/us/app/internet-status-online-or-not/id1039633009

https://mac-apps.appyogi.com/admin/php/productimages/Internet_status_SS1.png
https://mac-apps.appyogi.com/admin/php/productimages/Internet_status_SS2.png
https://mac-apps.appyogi.com/admin/php/productimages/Internet_status_SS3.png
https://mac-apps.appyogi.com/admin/php/productimages/Internet_status_SS4.png
https://mac-apps.appyogi.com/admin/php/productimages/Internet_status_SS5.png

So far I see for problematic I see the Desktop Icon has no Right Click Run as administrator?
I'd believe in constant motioning to the exact second like Internet Status and all its categories it exceeds, with the easy ability to get to and see.
Thank you.

**Comment by Rllyyy** [comment]
Thank you for contributing to Internet-Check. These are great suggestions.

I have spit up this request into multiple issues:
- Status Banner (notifyIcon.ShowBalloonTip()) on failed ping and when it's back (#95)
- Changing the minimum allowed interval to 1 second (#97)
- Bug: Desktop Icon is missing "Run as Administrator" (#96)

We are currently busy with building a UI for the settings in AdvancedSettings.xml, so fixing these issues and implementing the request might take some time.

**Comment by Rllyyy** [comment]
Please also use the latest Release v1.6.3 from the 15th of April 2021 found [here](https://github.com/Rllyyy/Internet-Check/releases/tag/v1.6.3)

**Comment by Rllyyy** [comment]
All request are now integrated in the app and should be available with release v1.6.4 coming sometime in the next two weeks. If you have any more suggestions we are happy to hear about them. Please consider [supporting](https://github.com/sponsors/Rllyyy?frequency=one-time&sponsor=Rllyyy) us even with a one time payment.
